### PR TITLE
Incorporate updates to draft

### PR DESCRIPTION
**Pull request by clintwilson**
Version for review by proposer+endorsers

### CODE REVIEW

**Comment by sleevi** [comment]
Did you mean as a draft PR? Otherwise, ready to merge :)

**Comment by clintwilson** [comment]
> 
> 
> Did you mean as a draft PR? Otherwise, ready to merge :)
Yeah, I guess I wanted to wait for Tim and Wayne to respond with whether they would still support this version of a charter before merging.

**Comment by sleevi** [comment]
Well, you made the PR to my list of requested edits, so why don't I merge those in?

Right now, my understanding of the branches are:
- https://github.com/sleevi/cabforum-docs/tree/2020-03-13-SMCWG_Charter exactly as you originally circulated, without edits ( https://github.com/cabforum/documents/pull/167 )
- https://github.com/sleevi/cabforum-docs/tree/SMCWG-draft-feedback Google's feedback on said draft charter ( https://github.com/sleevi/cabforum-docs/pull/9 )
- https://github.com/timfromdigicert/documents/tree/SMCWG-charter-draft-2020-04-01 @timfromdigicert's fork, which incorporates some of the above feedback (no known PR? I think Tim just did his own thing here)

Your pull is on Google's feedback, and it all works for me. I think if there are concerns from @wthayer or @timfromdigicert , we could perhaps continue in https://github.com/sleevi/cabforum-docs/pull/9 and see if we can't find a way to address all of that feedback? I'm flexible to keep editing that branch to see if we can get something workable.

**Comment by clintwilson** [comment]
I realized I never directly replied; sorry about that. I'm good with this being merged.

**Pull request merged**
